# Generated by Django 5.1.4 on 2025-03-12 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citta', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tratta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partenza', models.CharField(max_length=20)),
                ('destinazione', models.CharField(max_length=20)),
                ('tipo_corsa', models.CharField(max_length=20)),
                ('ora', models.TimeField(default='00:00')),
                ('prezzo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tratta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tratta')),
            ],
        ),
    ]
