# Generated by Django 5.1.4 on 2025-03-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tratta',
            old_name='destinazione',
            new_name='arrivo',
        ),
    ]
