# Generated by Django 5.1.7 on 2025-06-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_destinazione_tratta_arrivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
    ]
