# Generated by Django 5.1.7 on 2025-07-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_utenti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utenti',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
