# Generated by Django 5.1.7 on 2025-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_utenti_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citta',
            name='citta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tratta',
            name='arrivo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tratta',
            name='partenza',
            field=models.CharField(max_length=100),
        ),
    ]
