# Generated by Django 5.1.7 on 2025-07-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_citta_citta_alter_tratta_arrivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utenti',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
